spring:
  datasource:
    username: root
    password: Lenkeran5566
    url: jdbc:mysql://localhost:3306/my_database
  jpa:
    show-sql: true

  liquibase:
    change-log: classpath:liquibase/changelog-master.yml

